### ISSUE TITLE
Allsymbols keyerror

### ISSUE THREAD

**Issue by Pusherman2** [tpmmthomas/binance-copy-trade-bot-old#1]
Hi there, I love this idea for this project!

However, I am facing some errors unfortunately and hoping you could provide me some insight on how to resolve them :)

I setup everything correctly, however, I am getting a keyerror.
I followed the steps in Telegram, the keyerror appears after inputting the SL value. 

Please find the debug log below:

`2021-08-27 21:22:25,998 - __main__ - INFO - No data to restore.
2021-08-27 21:22:26,003 - apscheduler.scheduler - INFO - Scheduler started
2021-08-27 21:22:37,771 - __main__ - INFO - AA is doing authentication check.
2021-08-27 21:22:39,520 - __main__ - INFO - AA has agreed to the disclaimer.
2021-08-27 21:23:04,845 - __main__ - INFO - AA has entered the first url.
2021-08-27 21:23:31,032 - __main__ - ERROR - APIError(code=-4059): No need to change position side.
2021-08-27 21:23:31,266 - __main__ - ERROR - APIError(code=-4046): No need to change margin type.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/User/Documents/binance-copy-trade-bot/mon_position.py", line 1184, in initTraderThread
    CurrentUsers[chat_id] = users(
  File "/home/User/Documents/binance-copy-trade-bot/mon_position.py", line 4878, in __init__
    thr = FetchLatestPosition(
  File "/home/User/Documents/binance-copy-trade-bot/mon_position.py", line 368, in __init__
    self.reload()
  File "/home/User/Documents/binance-copy-trade-bot/mon_position.py", line 794, in reload
    allsymbols = CurrentUsers[self.chat_id].bclient.get_symbols()
KeyError: 803092140`

Running Ubuntu 20.04, python3.9 and everything setup within a virtualenv with all required dependencies installed.

Thanks and kind regards,

Pusherman2

**Comment by tpmmthomas** [comment]
Hi Pusherman2,

Thanks a lot for your interest in our project!! Please note that the program is still being tested by us and there has not been officially released versions yet. There could possibly be serious bugs and cost you a real lost of funds. Make sure you understand the risks before using. 

As for the bug you have mentioned, I confirm that it is a bug from our program, which I have just fixed :)
I also realised that there are some fields missing from constants_sample.py, please redownload again and fill in those fields before running.
