### ISSUE TITLE
Binance futures exchange info

### ISSUE THREAD

**Issue by Pat2018-1** [tpmmthomas/binance-copy-trade-bot-old#2]
Hi,

when i setup the trader that i want to follow i get this
DevTools listening on ws://127.0.0.1:61243/devtools/browser/fc6120e9-96a6-4f55-bc85-e4bf51ee9c99
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\patri\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\patri\Desktop\binance-copy-trade-bot-main\binance-copy-trade-bot-main\mon_position.py", line 1277, in initTraderThread
    CurrentUsers[chat_id] = users(
  File "C:\Users\patri\Desktop\binance-copy-trade-bot-main\binance-copy-trade-bot-main\mon_position.py", line 5234, in __init__
    self.bclient = BinanceClient(
  File "C:\Users\patri\Desktop\binance-copy-trade-bot-main\binance-copy-trade-bot-main\mon_position.py", line 4510, in __init__
    info = self.client.futures_exchange_info()
AttributeError: 'Client' object has no attribute 'futures_exchange_info'

**Comment by tpmmthomas** [comment]
What is your environment?

**Comment by Pat2018-1** [comment]
python3.9

**Comment by Pat2018-1** [comment]
![image](https://user-images.githubusercontent.com/57678225/134469407-6523968a-1191-4341-a404-23981171ac8c.png)

**Comment by tpmmthomas** [comment]
Please check the following, Cos I don't encounter the problem you described.:
1. Did you use conda environment to avoid dependency conflicts?
2. Did you make sure you installed all dependencies as in requirements.txt ? (Errors might occur when you "pip install -r requirements.txt"  with different OS, if there are any problems regarding this step please tell me)
3. Also make sure that you only run mon_position.py.
